cp super_0.log super_3.log
cp super_0.log super_4.log
cp super_0.log super_5.log
cp super_0.log super_6.log
cp super_0.log super_7.log
cp super_0.log super_8.log
cp super_0.log super_9.log
cp super_0.log super_10.log
cp super_0.log super_11.log
cp super_0.log super_12.log
cp super_0.log super_13.log
cp super_0.log super_14.log
cp super_0.log super_15.log
cp super_0.log super_17.log
cp super_0.log super_17.log
cp super_0.log super_18.log
cp super_0.log super_19.log
cp super_0.log super_20.log
cp super_0.log super_21.log
cp super_0.log super_22.log
cp super_0.log super_23.log
cp super_0.log super_24.log
cp super_0.log super_25.log
cp super_0.log super_26.log
cp super_0.log super_27.log
cp super_0.log super_28.log
cp super_0.log super_29.log
